[package]
name = "kata_draw"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
slint = {version="1.10.0", features=["renderer-winit-software"]}

[build-dependencies]
slint-build = "1.10.0"
