config:
  month_dict:
    1: 'LEDEN'
    2: 'ÚNOR'
    3: 'BŘEZEN'
    4: 'DUBEN'
    5: 'KVĚTEN'
    6: 'ČERVEN'
    7: 'ČERVENEC'
    8: 'SRPEN'
    9: 'ZÁŘÍ'
    10: 'ŘÍJEN'
    11: 'LISTOPAD'
    12: 'PROSINEC'

  cat_to_col_dict:
    MU14: 15
    WU14: 16
    MU16: 15
    WU16: 16
    MU18-CSJU: 11
    MU18-EJU: 12
    WU18-CSJU: 13
    WU18-EJU: 14
    MU21-CSJU: 7
    MU21-EJU: 8
    WU21-CSJU: 9
    WU21-EJU: 10
    M-CSJU: 3
    M-EJU: 4
    W-CSJU: 5
    W-EJU: 6
    ost: 16

  origin_dict:
    EJU: ['#00b0f0', 'EJU - Evropský pohár - uzavřený']
    EJU-Open: ['#00b0f0', 'EJU - Evropský pohár - otevřený', '#ff0000']
    MCR: ['#e46c0a', 'ČSJU - Přebor, mistrovství ČR']
    CSJU: ['#92d050', 'ČSJU - Český pohár']
    DL: ['#c6d9f1', 'ČSJU - DL, I. L, EXL']
    PK: ['#ffc000', 'KSJu PK']
    JC: ['#ffff00', 'KSJu JČ']
    KK: ['#ffccff', 'KSJu KK']
    NEP: ['#AAAAAA', 'Zatím nepotvrzené souteže KSJu PK']

