config:
  month_dict:
    1: 'LEDEN'
    2: 'ÚNOR'
    3: 'BŘEZEN'
    4: 'DUBEN'
    5: 'KVĚTEN'
    6: 'ČERVEN'
    7: 'ČERVENEC'
    8: 'SRPEN'
    9: 'ZÁŘÍ'
    10: 'ŘÍJEN'
    11: 'LISTOPAD'
    12: 'PROSINEC'

  cat_to_col_dict:
    U8: 15
    U10: 15
    MU12: 13
    WU12: 14
    MU14: 11
    WU14: 12
    MU16: 9
    WU16: 10
    MU18: 7
    WU18: 8
    MU21: 5
    WU21: 6
    M: 3
    W: 4
    ost: 16

  origin_dict:
    EJU: ['#00b0f0', 'EJU - Evropský pohár']
    MCR: ['#e46c0a', 'ČSJU - Přebor, mistrovství ČR']
    CSJU: ['#92d050', 'ČSJU - Český pohár']
    DL: ['#c6d9f1', 'ČSJU - DL, I. L, EXL']
    PK: ['#ffc000', 'KSJu PK']
    JC: ['#ffff00', 'KSJu JČ']
    KK: ['#ffccff', 'KSJu KK']
    NEP: ['#AAAAAA', 'Zatím nepotvrzené souteže KSJu PK']

